theme: minima
title: Ryusei-code
author: Ryusei
description: In this page, I show the production I made, I have begun programming since I entered university.
So, there are a lot of poor codes. The people who need my code should seek other people's code.
I'm sorry, Hige sorry!
